.SUFFIXES: .cxx .cu .f90 .o
.PHONY: docs

CUDA_INSTALL_PATH = /usr/local/cuda

DEVICE  = gpu

CXX     = mpicxx -g -O3 -std=c++11 -fPIC -fopenmp -ffast-math -funroll-loops -rdynamic -Wfatal-errors -I../include
NVCC    = nvcc -Xcompiler "-fopenmp -O3" -std=c++11 -use_fast_math -I../include

LFLAGS  += -lcudart

OBJECT  = ../kernel/$(DEVICE)Laplace.o

.cxx.o:
	$(CXX) -c $? -o $@ $(LFLAGS)
.cu.o:
	$(NVCC) -c $? -o $@ $(LFLAGS)
.f90.o:
	$(FC) -c $? -o $@

